services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: translation_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - ./docker-volumes/mailhog:/data

  redis:
    image: redis:alpine
    container_name: translation_redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis:/data
